title: Page
pages: false
files:
  fields:
    caption:
      label: Description
      type: textarea
      buttons:
        - bold
        - italic
        - link
        - email
fields:
  autoid:
    type: hidden
  previewfiles:
    type: previewfiles
  reveal: reveal
  title:
    label: Titre
    type:  text
  text:
    label: Texte
    type:  simplemde