title: Site
fields:
  generalSettings:
    label: Général
    type: headline
  title:
    label: Titre
    type:  text
  description:
    label: Description
    type:  simplemde
  keywords:
    label: Keywords
    type:  tags
  customcss:
    label: Custom CSS
    type: textarea
    buttons: false
  googleAnalytics:
    label: Google Analytics ID
    type: text
    icon: code
    help: Tracking ID in the form UA-XXXXXXXX-X. Keep this field empty if you are not using it.
    width: 1/2
  ogimage:
    label: Facebook OpenGraph image
    type: image
    help: 1200x630px minimum
    width: 1/2
  placeSettings:
    label: Infos pratiques
    type: headline
  address:
    label: Adresse
    type: simplemde
  openingHours:
    label: Heures d'ouverture
    type: simplemde
  contact:
    label: Contact
    type: simplemde
  socials:
    label: Réseaux sociaux
    type: structure
    style: table
    fields:
      title:
        label: Title
        type: text
        required: true
      url:
        label: URL
        type: url
        required: true
  footer:
    label: Footer
    type: simplemde
  legalPage:
    label: Mentions légales
    type: select
    options: pages
    width: 1/2
  # creditsPage:
  #   label: Crédits
  #   type: select
  #   options: pages
  #   width: 1/2