title: Site
files:
  fields:
    link:
      label: Link
      type: url
fields:
  generalSettings:
    label: Général
    type: tabs
  title:
    label: Titre
    type:  text
  description:
    label: Description
    type:  simplemde
  keywords:
    label: Keywords
    type:  tags
  customcss:
    label: Custom CSS
    type: textarea
    buttons: false
  googleAnalytics:
    label: Google Analytics ID
    type: text
    icon: code
    help: Tracking ID in the form UA-XXXXXXXX-X. Keep this field empty if you are not using it.
    width: 1/2
  ogimage:
    label: Facebook OpenGraph image
    type: image
    help: 1200x630px minimum
    width: 1/2
  tabs2:
    label: Menu
    type: tabs
  menu:
    label: Menu
    type: engineer
    fieldsets:
      page:
        label: Page
        fields:
          page:
            label: Page
            type: quickselect
            options: query
            required: true
            query:
              page: /
              fetch: index
              value: '{{autoid}}'
              text: '{{title}} ({{uri}})'
            width: 1/2
          bold:
            label: Titre en gras
            type: toggle
            width: 1/2
  logosMenu:
    label: Logos Menu
    type: images
  tabs3:
    label: Footer
    type: tabs
  contactEmail:
    label: Contact
    type: email
  socials:
    label: Réseaux sociaux
    type: engineer
    fieldsets:
      link:
        label: Link
        fields:
          title:
            label: Title
            type: text
            required: true
            width: 1/2
          icon:
            label: Icone
            type: select
            options: images
            width: 1/2
          link:
            label: URL
            type: url
            required: true
  footer1:
    label: Footer Colonne 1
    type: simplemde
  footer2:
    label: Footer Colonne 2
    type: simplemde
  mailchimp:
    label: Mailchimp
    type: url
  pressPage:
    label: Page presse
    type: quickselect
    options: query
    query:
      page: /
      fetch: index
      value: '{{autoid}}'
      text: '{{title}} ({{uri}})'
    width: 1/2
  legalPage:
    label: Mentions légales
    type: quickselect
    options: query
    query:
      page: /
      fetch: index
      value: '{{autoid}}'
      text: '{{title}} ({{uri}})'
    width: 1/2
  logos:
    label: Logos
    type: images
  # creditsPage:
  #   label: Crédits
  #   type: select
  #   options: pages
  #   width: 1/2
